import './landing.scss'
import '../headers-footers/headers-footers.scss'
import '../../blocks/headers-footers/header/header'
import '../../blocks/headers-footers/header/header.scss'
import '../../blocks/headers-footers/menu/menu'
import '../../blocks/headers-footers/menu/menu.scss'
import '../../blocks/headers-footers/mobile-menu/mobile-menu'
import '../../blocks/headers-footers/mobile-menu/mobile-menu.scss'
import '../../blocks/form-elements/buttons/buttons.scss'
import '../../blocks/cards/find-apartments-card/find-apartments-card'
import '../../blocks/headers-footers/footer/footer'
import '../../blocks/headers-footers/footer/footer.scss'
import '../../assets/scss/fonts.scss'

console.log('in landing.js')