import './registration.scss'
import '../../blocks/cards/register-account-card/register-account-card'
import '../headers-footers/headers-footers.scss'
import '../../blocks/headers-footers/header/header'
import '../../blocks/headers-footers/header/header.scss'
import '../../blocks/headers-footers/menu/menu'
import '../../blocks/headers-footers/menu/menu.scss'
import '../../blocks/headers-footers/mobile-menu/mobile-menu'
import '../../blocks/headers-footers/mobile-menu/mobile-menu.scss'
import '../../blocks/form-elements/buttons/buttons.scss'
import '../../blocks/headers-footers/footer/footer'
import '../../blocks/headers-footers/footer/footer.scss'
import '../../assets/scss/fonts.scss'

console.log('in registration.js')