import 'jquery'
import 'air-datepicker'
import './cards.scss'
import '../../blocks/form-elements/calendar/calendar'
import '../../blocks/form-elements/calendar/calendar.scss'
import '../../blocks/form-elements/dropdown/dropdown'
import '../../blocks/form-elements/dropdown/dropdown.scss'
import '../../blocks/form-elements/buttons/buttons.scss'
import '../../blocks/form-elements/text-field/text-field.scss'
import '../../blocks/form-elements/radio-btn/radio-btn.scss'
import '../../blocks/form-elements/toggle/toggle.scss'
import '../../blocks/cards/enter-card/enter-card.scss'
import '../../blocks/form-elements/rate-btn/rate-btn.scss'
import '../../blocks/cards/booking/booking.scss'
import '../../blocks/cards/gallery/gallery.scss'
import '../../assets/scss/fonts.scss'

console.log('in cards.js')